### ISSUE TITLE
the given value is not valid for variable 'client_cidr_block'  

### ISSUE THREAD

**Issue by pastorismylord** [joatmon08/hashicorp-stack-demoapp#2]
I'm getting this error when trying to complete the infrastructure plan on terraform: The given value is not valid for variable "client_cidr_block": list of string required.

The issue seems to be that the type changed on this version: https://github.com/joatmon08/hashicorp-stack-demoapp/commit/1aa6b9d396946aace3a53aa9026682a49c3a7c17

Maybe the readme.md needs updating? Particularly: client_cidr_block (sensitive): public IP address of your machine, in 00.00.00.00/32 form. You get it by running curl ifconfig.me in your terminal.

**Comment by joatmon08** [comment]
Good catch! Thanks, @pastorismylord. I updated the `README` to reflect the changes. I changed it to a list type since I had multiple endpoints accessing Boundary at one point.
